require('plugins')
require("mason_configs")
require('general')
require("themes_configs")
require('lsp')
require('treesitter')
require('telescope_configs')
require('lualine_configs')
require('mapping')
--require('tabnine_configs')

